version: '3'

services:
  app:
    build: .
    image: burachat_1.1.0/app:1.1.0 # update 1.1.0 and in terminal
    container_name: my_app_1.1.0
    ports:
      - "8081:13377" # ภายนอก:ภายใน 1.0 8080/1337
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=5437
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=false
  db:
    image: postgres:latest
    container_name: my_db
    ports:
      - "5437:5432" # ภายนอก:ภายใน 1.0 5436
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      
    
