version: '3'

services:
  app:
    build: .
    image: burachat/app:1.0.0 # update 1.1.0 and in terminal
    container_name: my_app
    ports:
      - "8080:1337" # ภายนอก:ภายใน
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=5436
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=false
  db:
    image: postgres:latest
    container_name: my_db
    ports:
      - "5436:5432" # ภายนอก:ภายใน
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      
    
