version: '3'

services:
  app:
    #build: .
    image: burachat/app:1.0.0
    container_name: my-app
    ports:
      - 1337:1337
    env_file:
      - .env

  db:
    image: postgres:15.5-bullseye
    container_name: my-db
    ports:
      - 5432:5432
    env_file:
      - .env
      
    
